appdata:
    build: containers/app-data/
    volumes:
        - /var/www/silex

pgsqldata:
    build: containers/pgsql-data/
    volumes:
        - /var/lib/postgresql/data

pgsql:
    image: postgres:9.4
    volumes_from:
        - pgsqldata
    expose:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: silex
        POSTGRES_USER : silex

redis:
    image: redis:3.0
    expose:
        - 6379:6379
        
phpfpm:
    mem_limit: 1000000000
    build: containers/phpfpm/
    expose:
        - 9000:9000
    links:
        - pgsql
        - redis
    volumes_from:
        - appdata
    environment:
        POSTGRES_PASSWORD: silex
        POSTGRES_USER: silex
        POSTGRES_PORT: 5432
        POSTGRES_HOST: http://pgsql

nginx:
    build: containers/nginx/
    ports:
        - 80:80
    links:
        - phpfpm
    volumes_from:
        - appdata
    environment:
        VHOST: silex.loc
