app:
    build: containers/symfony/
    volumes:
        - /var/www/symfony
    tty: true

pgsqldata:
    build: containers/pgsql-data/
    volumes:
        - /var/lib/postgresql/data
    tty: true
    
pgsql:
    image: postgres:9.4.1
    volumes_from:
        - pgsqldata
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: symfony
        POSTGRES_USER : symfony
        
phpfpm:
    build: containers/phpfpm/
    expose:
        - 9000:9000
    links:
        - pgsql
    volumes_from:
        - app

nginx:
    build: containers/nginx/
    ports:
        - 80:80
    links:
        - phpfpm
    volumes_from:
        - app