app:
    build: containers/symfony/
    volumes:
        - /var/www/symfony
    tty: true

#db:
#    image: mysql
#    ports:
#        - 3306:3306
#    environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: symfony
#        MYSQL_USER: root
#        MYSQL_PASSWORD: root

phpfpm:
    build: containers/phpfpm/
    expose:
        - 9000:9000
#    links:
#        - db
    volumes_from:
        - app

nginx:
    build: containers/nginx/
    ports:
        - 80:80
    links:
        - phpfpm
    volumes_from:
        - app